# Site settings
title: Dilan Nery Lopes
email: dnerylopes@gmail.com.br
description: ""
baseurl: ""
url: "http://dilan.com.br"
twitter_username: dilannery
github_username:  dnerylopes

# Build settings
markdown: kramdown
permalink: pretty
